version: '3.3'
services:
  nginx:
    build:
      context: nginx
      dockerfile: .docker/Dockerfile
    image: ${NGINX_IMAGE}
    container_name: ${NGINX_CONTAINER}
    ports:
      - 80:80
    depends_on:
      - php
    networks:
      - internal_network
  php:
    image: adrianet86/php-redis
#    build:
#      context: php
#      dockerfile: .docker/Dockerfile
#    image: ${PHP_IMAGE}
    container_name: ${PHP_CONTAINER}
    environment:
      - APP_ENV=prod
    working_dir: /app
    volumes:
      - ./php/src:/app
    ports:
      - 9000:9000
    networks:
      - internal_network

  redis:
    image: redis:4.0.5-alpine
    container_name: ${REDIS_CONTAINER}
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - internal_network
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  internal_network:
    driver: bridge
